# Uses Cygwin or MSYS (1.0 or 2.0) for bash, unzip, bzip2, wget, sed, etc.
# Python and Perl also needed
# If wget binary is not found, the python package wget is used

init:
  # Add any of the following:
  # 1. C:\\cygwin\\bin
  # 2. C:\\cygwin64
  # 3. C:\\MinGW\\msys\\1.0\\bin
  # 4. C:\\msys64
  - "SET PATH=%PATH%;C:\\msys64;c:\\Python27\\Scripts"
  - "ECHO PATH=%PATH%"
  - bash --version

install:
  - python -m pip install -r requirements.txt -r win-requirements.txt
  - "DIR c:\\Python27\\Scripts"

build: off

test_script:
  - bash -x fetch.sh
  # Create two schema scripts with tables prefixed era2010 and era2012
  - 'sed -re "s/(^CREATE TABLE|REFERENCES|CONSTRAINT) journal([_ ])/\1 era2010_journal\2/g" schema.sql > schema2010.sql'
  - 'sed -re "s/(^CREATE TABLE|REFERENCES|CONSTRAINT) journal([_ ])/\1 era2012_journal\2/g" schema.sql > schema2012.sql'

  # Remove the duplicate disciplines and the misplaced new lines from the ERA2010 journal list
  - mv ERA2010_journal_title_list.xml ERA2010_journal_title_list.xml.orig
  - python C:/Python27/Scripts/lxmlproc --output ERA2010_journal_title_list.xml era_journal_list_2010_tidy.xsl ERA2010_journal_title_list.xml.orig

  # Convert the xml to sql insert statements
  - perl era_journal_list_sql.pl ERA2010_journal_title_list.xml era2010 oracle > ERA2010_journal_title_list.sql
  - perl era_journal_list_sql.pl ERA2012_journal_title_list.xml era2012 oracle > ERA2012_journal_title_list.sql

cache:
  - .cache/era_xml -> fetch.sh

artifacts:
  - path: .cache/era_xml
    name: Raw data fetched and converted to XML
  - path: ERA2010_journal_title_list.xml
    name: Cleaned 2010 XML
  - path: '*201*s.sql'
    name: Schema (Oracle syntax) and data files
